---
title: "Crime Data (2017-2019, County Level)"
author: "Fanmei Xia"
date: "04/22/2021"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidycensus)
library(tidyverse)
library(tigris)
```


```{r NJ, message=FALSE, warning=FALSE}
# Read in the crime data from 2017 - 2019
crime_17 <- read.csv("crime_data_2017.csv")
crime_1819 <- read.csv("crime_data_2018-2019.csv")

```

```{r, message=FALSE, warning=FALSE}
sum_17 <- crime_17 %>%
  filter(Population == "") %>%
  group_by(CountyFIPS, County) %>%
  summarise(Co_tot = sum(Total), 
            Year = "2017")

sum_1819 <- crime_1819 %>%
  group_by(CountyFIPS, County, Year) %>%
  summarise(Co_tot = sum(Total))
sum_1819$Year <- as.character(sum_1819$Year)
            
# Create one dataset that has all three years' data
crime <- bind_rows(sum_17, sum_1819) %>%
  arrange(CountyFIPS) 
crime$CountyFIPS <- as.character(crime$CountyFIPS)

```

```{r}
#write_csv(crime, file = "crime_county.csv")
read.csv("crime_county.csv")
```

```{r}
crime %>%
  ggplot(
    aes(
      x = County, 
      y = Co_tot, 
      fill = as.factor(Year)
      )
    ) +
  geom_bar(
    position="dodge",
    stat = "identity", 
    width = 0.75
    ) +
    theme_classic() +
    labs(
        x = "County",
        y = "Total Crime Incidents",
        title = paste("Crime Data by County") 
    ) +
  coord_flip()
```

```{r, echo=FALSE, message=FALSE, warning=FALSE, include=FALSE, collapse = TRUE,}
# get the shapefile
options(tigris_class = "sf")
nj_counties<- counties(state="NJ", cb=T, year=2010)
nj_counties$cofips<-substr(nj_counties$GEO_ID, 10,15)

nj_crime <- geo_join(nj_counties, crime, by_sp="cofips", by_df="CountyFIPS")

```

```{r, echo=FALSE, message=FALSE, warning=FALSE}
# plot
nj_crime %>%
  filter(Year == "2017") %>%
  ggplot() +
  geom_sf(mapping=aes(fill=Co_tot)) +
  scale_fill_viridis_c() +
  scale_color_viridis_c() +
  ggtitle("Crime Data", subtitle = "New Jersey - county level")

```