---
title: "Distress Index from the ACS Data"
author: "Fanmei Xia"
date: "`r lubridate::today()`"
output: github_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(warning = FALSE)
```

```{r, include = FALSE}
library(tidyverse)
library(tidycensus)
library(sf)
library(tigris)
```

## 1. Import Data

```{r check_vars, include = FALSE, }
# check for available variables in the census data (in this case American Community Survey)
ACS18var <- load_variables(2018, "acs5", cache = TRUE)
view(ACS18var)
```

```{r }
# get data of interest by geography (tract)

## identify variables for NO HIGH SCHOOL DIPLOMA (percent of the 25-year-old population without a high school diploma or equivalent)
# 1. B06009_002: Estimate!!Total!!Less than high school graduate
# 2. B17024_054: Estimate!!Total!!25 to 34 years
# 3. B17024_067: Estimate!!Total!!35 to 44 years
# 4. B17024_080: Estimate!!Total!!45 to 54 years
# 5. B17024_093:	Estimate!!Total!!55 to 64 years
# 6. B17024_106:	Estimate!!Total!!65 to 74 years
# 7. B17024_119:	Estimate!!Total!!75 years and over
# 4. 

## identify variables for Housing Vancancy Rate (percent of habitable housing that is unoccupied, excluding properties that are for seasonal, recreational, or occational use)
#  1. total_units = "B25002_001",
#  2. occupied_units = "B25002_002",
#  3. vacant_units = "B25002_003"

## identify variables for Adults Not Working (percent of the prime age, 25-54, population not currently employed)
#  1. 

## identify variables for Poverty Rate (percent of the population living under poverty line)
#  1. 

## identify variables for Median Income Ratio (Median household income as a percent of of metro area median household income)
#  1. 

## identify variables for Change in Employment (percent change in the number of jobs from 2014-2018)
#  1. 

## identify variables for Change in Establishments (percent change in the number of business establishments from 2014 to 2018)
#  1. 

## identify variables for Median Income Ratio
#  1. 

distress_variables <- get_acs(
                state = "NJ",
                geography = "tract",
                variables = c(total_units = "B25002_001",
                              occupied_units = "B25002_002",
                              vacant_units = "B25002_003",
                              occupied_owner = "B25003_002",
                              occupied_renter = "B25003_003",
                              no_vehicle = "B08201_002",
                              public_transit = "B08301_010",
                              mobile_home = "B25024_010",
                              multiunits_two = "B25024_004",
                              multiunits_three_or_four = "B25024_005",
                              multiunits_five_to_nine = "B25024_006",
                              multiunits_10_to_19 = "B25024_007",
                              multiunits_20_to_49 = "B25024_008",
                              multiunits_50plus = "B25024_009",
                              pop_own_occ = "B25026_002",
                              pop_own_90_99 = "B25026_007",
                              pop_own_bfr89 = "B25026_008",
                              pop_ren_occ = "B25026_009",
                              pop_ren_90_99 = "B25026_014",
                              pop_ren_bfr89 = "B25026_015"
                              ),
                year = 2018,
                geometry = FALSE
                )

# cleaning
residential_data <- housing_acs %>% 
  select(GEOID, NAME, variable, estimate) %>% 
  spread(variable, estimate) %>% 
  mutate(
    occupancy_rate = occupied_units/total_units, 
    vacancy_rate = vacant_units/total_units,
    mobile_home_rate = mobile_home/total_units,
    multiunit_struct = multiunits_two + multiunits_three_or_four + multiunits_five_to_nine + multiunits_10_to_19 + multiunits_20_to_49 + multiunits_50plus,
    pop_own_20yrs_plus = pop_own_90_99 + pop_own_bfr89,
    pop_ren_20yrs_plus = pop_ren_90_99 + pop_ren_bfr89,
    pop_20yrs_plus = pop_own_20yrs_plus + pop_ren_20yrs_plus
    ) %>%
  select(GEOID,occupancy_rate, vacancy_rate, multiunit_struct, mobile_home_rate, pop_20yrs_plus, no_vehicle, public_transit, everything())

head(residential_data)

# Save as csv file
write_csv(residential_data, "residential_data.csv")
```


```{r }
# download shapefile
tract_shp <- tracts(state = 'NJ', year = 2018, cb = TRUE) 

```

