---
title: "racial_isolation_index"
author: "Fanmei Xia"
date: "2/14/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidycensus)
library(tidyverse)
library(tigris)
```


## Calculating Segregation
First we need to load some libraries. We use R to get all of our census data from the American Community Survey.

Below, we will use counties in New Jersey and use the 2015 ACS B03002 table. This table gives population estimates by race and Hispanic ethnicity.


```{r NJ }
## Getting data from the 2011-2015 5-year ACS
# check for available variables in the census data (in this case American Community Survey)
ACS18var <- load_variables(2018, "acs5", cache = TRUE)
view(ACS18var)

## Loading ACS5 variables for 2015 from table B03002 and caching the dataset for faster future access.
race_table <-  get_acs(geography = "tract", year=2015, geometry = F, output="wide", table = "B03002", cache_table = T, state = "NJ")

trdat<-race_table%>%
  mutate(nhwhite=B03002_003E,
         nhblack=B03002_004E,
         nhasian=B03002_006E,
         nhother= B03002_005E+B03002_007E+B03002_008E+B03002_009E+B03002_010E,
         hisp=B03002_012E, 
         total=B03002_001E,
         year=2015,
         cofips=substr(GEOID, 1,5))%>%
  select(GEOID, nhwhite, nhblack, nhasian, hisp, nhother, total, year, cofips )%>%
  arrange(cofips, GEOID)

#look at the first few cases
head(trdat)
```

