---
title: "Retrieving ACS Data"
author: "Fanmei Xia"
date: "`r lubridate::today()`"
output: github_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(warning = FALSE)
```

```{r, include = FALSE}
library(tidyverse)
library(tidycensus)
library(sf)
library(tigris)
```

## 1. Import Data

```{r access_data, include = FALSE}
# to obtain a census api go here https://api.census.gov/data/key_signup.html
# to access the census data remove '#' enter your own API key below

# census_api_key(42f846433970adad431d7c983bdd0d445ada8428", install=TRUE)

# Note: doing this once is enough for R. Tidycensus includes census_api_key() which automatically stores your key in .Renviron. You can use "tidycensus" anytime without re-entering your API key.
```

```{r check_vars, include = FALSE, }
# check for available variables in the census data (in this case American Community Survey)
ACS18var <- load_variables(2018, "acs5", cache = TRUE)
view(ACS18var)
```

```{r }
# get data of interest by geography (tract)

## identify variables from B25002: OCCUPANCY STATUS
#  1. Total Units           B25002_001 Estimate!!Total	
#  2. Occupancy : Occupied  B25002_002 Estimate!!Total!!Occupied	
#  3. Occupancy : Vacant    B25002_003 Estimate!!Total!!Vacant	

## identify variables from B25024: UNITS IN STRUCTURE
#  1. Type : Mobile home    B25024_010	Estimate!!Total!!Mobile home, Base B25024_001 should be same as B25002_001
#  2. Type : Multi-units-2    B25024_004	Estimate!!Total!!2
#  3. Type : Multi-units-3or4    B25024_005		Estimate!!Total!!3 or 4
#  4. Type : Multi-units-5to9    B25024_006		Estimate!!Total!!5 to 9	
#  5. Type : Multi-units-10-19    B25024_007		Estimate!!Total!!10 to 19
#  6. Type : Multi-units-20-49    B25024_008		Estimate!!Total!!20 to 49
#  7. Type : Multi-units-50+    B25024_009		Estimate!!Total!!50 or more

## identify variables from B25003 : TENURE
#  1. Status: Occupied        B25003_001 Estimate!!Total	Occupied Units
#  2. Status: Owner Occupied  B25003_002 Estimate!!Total!!Owner occupied Units
#  3. Status: Renter Occupied B25003_003 Estimate!!Total!!Renter occupied Units

## identify variables from B08201 : HOUSEHOLD SIZE BY VEHICLES AVAILABLE
# 1. Type: No Vehicle Available B08201_002 Estimate!!Total!!No vehicle available

## identify variables from B08301 : MEANS OF TRANSPORTATION TO WORK
# 1. Type: Public Transportation B08301_010 	Estimate!!Total!!Public transportation (excluding taxicab)

## identify variables from B25026: TOTAL POPULATION IN OCCUPIED HOUSING UNITS BY TENURE BY YEAR HOUSEHOLDER MOVED INTO UNIT
#  1. Year : Tot Pop   OwnOcc B25026_002 Estimate!!Total population in occupied housing units!!Owner occupied	
#  2. Year : 1990_1999 OwnOcc B25026_007 Estimate!!Total population in occupied housing units!!Owner occupied!!Moved in 1990 to 1999
#  3. Year : <1989     OwnOcc B25026_008 Estimate!!Total population in occupied housing units!!Owner occupied!!Moved in 1989 or earlier	
#  4. Year : Tot Pop   RenOcc B25026_009	Estimate!!Total population in occupied housing units!!Renter occupied	
#  5. Year : 1990_1999 RenOcc B25026_014 Estimate!!Total population in occupied housing units!!Renter occupied!!Moved in 1990 to 1999	
#  6. Year : <1989     RenOcc B25026_015 Estimate!!Total population in occupied housing units!!Renter occupied!!Moved in 1989 or earlier

housing_acs <- get_acs(
                state = "NJ",
                geography = "tract",
                variables = c(total_units = "B25002_001",
                              occupied_units = "B25002_002",
                              vacant_units = "B25002_003",
                              occupied_owner = "B25003_002",
                              occupied_renter = "B25003_003",
                              no_vehicle = "B08201_002",
                              public_transit = "B08301_010",
                              mobile_home = "B25024_010",
                              multiunits_two = "B25024_004",
                              multiunits_three_or_four = "B25024_005",
                              multiunits_five_to_nine = "B25024_006",
                              multiunits_10_to_19 = "B25024_007",
                              multiunits_20_to_49 = "B25024_008",
                              multiunits_50plus = "B25024_009",
                              pop_own_occ = "B25026_002",
                              pop_own_90_99 = "B25026_007",
                              pop_own_bfr89 = "B25026_008",
                              pop_ren_occ = "B25026_009",
                              pop_ren_90_99 = "B25026_014",
                              pop_ren_bfr89 = "B25026_015"
                              ),
                year = 2018,
                geometry = FALSE
                )

# cleaning
residential_data <- housing_acs %>% 
  select(GEOID, NAME, variable, estimate) %>% 
  spread(variable, estimate) %>% 
  mutate(
    occupancy_rate = occupied_units/total_units, 
    vacancy_rate = vacant_units/total_units,
    mobile_home_rate = mobile_home/total_units,
    multiunit_struct = multiunits_two + multiunits_three_or_four + multiunits_five_to_nine + multiunits_10_to_19 + multiunits_20_to_49 + multiunits_50plus,
    pop_own_20yrs_plus = pop_own_90_99 + pop_own_bfr89,
    pop_ren_20yrs_plus = pop_ren_90_99 + pop_ren_bfr89,
    pop_20yrs_plus = pop_own_20yrs_plus + pop_ren_20yrs_plus
    ) %>%
  select(GEOID,occupancy_rate, vacancy_rate, multiunit_struct, mobile_home_rate, pop_20yrs_plus, no_vehicle, public_transit, everything())

head(residential_data)

# Save as csv file
write_csv(residential_data, "residential_data.csv")
```


```{r }
# download shapefile
tract_shp <- tracts(state = 'NJ', year = 2018, cb = TRUE) 

```

