---
title: "Social Vulnerability Index (Municipality Level)"
author: "Fanmei Xia"
date: "04/22/2021"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidycensus)
library(tidyverse)
library(tigris)
```


```{r NJ, message=FALSE, warning=FALSE}
## Getting data from CDC SVI website (2018, New Jersey)
# check for available variables in the data
setwd("/Users/xiafm/Documents/GitHub/NJ-opioidenv/data_raw")
svi <- read_csv("SVI-NewJersey2018.csv")
svi$FIPS <- as.character(svi$FIPS)
svi <- na_if(svi, '-999') 
```

```{r, message=FALSE, warning=FALSE}
#Merge with the interpolation 
path <- ("/Users/xiafm/Documents/GitHub/NJ-opioidenv/data_final/")
interpolation <- read_csv(paste0(path, "cw_areal_interpolation.csv"))
interpolation$TRACTID <- as.character(interpolation$TRACTID)

tr_mun <- left_join(x = interpolation, y = svi, by = c("TRACTID" = "FIPS"))
```

```{r, message=FALSE, warning=FALSE}
#We need the municipality-level totals for the RPL themes
weighted <- tr_mun %>%
  mutate(weighted_SPL_THEME1 = SPL_THEME1*prop_of_ct,
         weighted_RPL_THEME1 = RPL_THEME1*prop_of_ct,
         weighted_SPL_THEME2 = SPL_THEME2*prop_of_ct,
         weighted_RPL_THEME2 = RPL_THEME2*prop_of_ct,
         weighted_SPL_THEME3 = SPL_THEME3*prop_of_ct,
         weighted_RPL_THEME3 = RPL_THEME3*prop_of_ct,
         weighted_SPL_THEME4 = SPL_THEME4*prop_of_ct,
         weighted_RPL_THEME4 = RPL_THEME4*prop_of_ct,
         weighted_SPL_THEMES = SPL_THEMES*prop_of_ct,
         weighted_RPL_THEMES = RPL_THEMES*prop_of_ct
         )

mun_sum <- weighted %>%
  group_by(SSN) %>%
  mutate(mun_SPL_THEME1 = sum(weighted_SPL_THEME1), 
         mun_RPL_THEME1 = sum(weighted_RPL_THEME1),
         mun_SPL_THEME2 = sum(weighted_SPL_THEME2), 
         mun_RPL_THEME2 = sum(weighted_RPL_THEME2), 
         mun_SPL_THEME3 = sum(weighted_SPL_THEME3), 
         mun_RPL_THEME3 = sum(weighted_RPL_THEME3),
         mun_SPL_THEME4 = sum(weighted_SPL_THEME4), 
         mun_RPL_THEME4 = sum(weighted_RPL_THEME4),
         mun_SPL_THEMES = sum(weighted_SPL_THEMES),
         mun_RPL_THEMES = sum(weighted_RPL_THEMES)
         )

svi_mun <- mun_sum %>%
  select(Place.Name, SSN, 
         mun_SPL_THEME1, mun_RPL_THEME1,
         mun_SPL_THEME2, mun_RPL_THEME2,
         mun_SPL_THEME3, mun_RPL_THEME3,
         mun_SPL_THEME4, mun_RPL_THEME4,
         mun_SPL_THEMES, mun_RPL_THEMES
         )
  
svi_mun <- unique(svi_mun)
```

```{r}
#write_csv(svi_mun, file = "svi_mun.csv")
read.csv("svi_mun.csv")
```
