# Dataset Name # 

- Meta Data Name: Percent of all land of municipality that is state/local/nonprofit open land
- Date Last Modified: Feb 1, 2022
- Author: Christian Villanueva
- Data File Name: ParkArea.csv
- Programming File Name(s): code/park_area.R
- Data Location: data_in_progress/measures for final dataset/ParkArea.csv

## DATA SOURCE(S):
Data pulled from New Jersey Geographic Information Network (NJGIN) https://njogis-newjersey.opendata.arcgis.com/datasets/4a1f9d3075a04cd792a14f78b9697df3/explore?location=40.307039%2C-74.074046%2C13.71

## DESCRIPTION OF DATA FILE: 
Percent of all land of municipality that is state/local/nonprofit open land

## DESCRIPTION OF DATA MANIPULATION:
1. Aggregate park area by municipality
2. Divide by total municipal area

## KEY VARIABLE NAMES AND DEFINITIONS:
SSN: Municipal identifier
MUN: Municipality name
ratio: ratio of park area to municipal area
## LINK TO DESCRIPTIVE STATISTICS:

## DATA LIMITIONS:
/

## COMMENTS/NOTES:  

## ACKNOWLEDGEMENTS:  
This project is supported by the National Institute of Drug Abuse at the National Institutes of Health (R21 DA046739-01A1; Developing a public health measure of built environment to assess risk of nonmedical opioid use and related mortality in urban and non-urban areas in New Jersey). 

## REFERENCES:
